name: Run Python Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.12
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name : Run pyenv
        run: . env/bin/activate
      
      - name : installation de pytest
        run: python -m pip install pytest
        
      - name : run flask
        env: 
          FLASK_APP: ${{ secrets.FLASK_APP }}
          DB_HOST : ${{ secrets.DB_HOST }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          API_KEY_COIN: ${{ secrets.API_KEY_COIN }}
        run: |
          export FLASK_ENV=development
          export FLASK_APP=run
          export DB_HOST="wb39lt71kvkgdmw0.cbetxkdyhwsb.us-east-1.rds.amazonaws.com"
          export DB_USERNAME=prtwpb7v8hv3ti8u
          export DB_PASSWORD=d6e8edsvxa2bju44
          export DB_DATABASE=atsp62l7dqdqz9ve
          export API_KEY_COIN=3144c6fc-815d-46d1-a588-60bc4e062a5c
          flask run
          pytest -p no:warnings 
          
        
      - name: Run tests with pytest
        run: pytest -p no:warnings 
