name: Run Python Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.12
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name : Run pyenv
        run: . env/bin/activate
      
      - name : installation de pytest
        run: python -m pip install pytest
        
      - name : run flask
        env: 
          FLASK_APP: ${{ secrets.FLASK_APP }}
          DB_HOST : ${{ secrets.DB_HOST }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          API_KEY_COIN: ${{ secrets.API_KEY_COIN }}
        run: |
          export FLASK_ENV=development
          export FLASK_APP=${{ env.FLASK_APP }}
          export DB_HOST=${{ env.DB_HOST }}
          export DB_USERNAME=${{ env.DB_USERNAME }}
          export DB_PASSWORD=${{ env.DB_PASSWORD }}
          export DB_DATABASE=${{ env.DB_DATABASE }}
          export API_KEY_COIN=${{ env.API_KEY_COIN }}
          flask run
          pytest -p no:warnings 
          
        
      - name: Run tests with pytest
        run: pytest -p no:warnings 
