name: Run Python Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    environment: studi-crypto-tracker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.12
      - name: setup-chromedriver
        uses: nanasess/setup-chromedriver@v1.0.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name : Run pyenv
        run: . env/bin/activate
        
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_FLASK_ENV: development
          envkey_FLASK_APP: run
          envkey_DB_HOST: ${{ secrets.DB_HOST }}
          envkey_DB_USERNAME: ${{ secrets.DB_USERNAME }}
          envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          envkey_DB_DATABASE: ${{ secrets.DB_DATABASE }}
          envkey_API_KEY_COIN: ${{ secrets.API_KEY_COIN }}
          file_name: .env
          
      - name : installation de pytest
        run: python -m pip install pytest pytest-dotenv pytest-flask selenium
        
      - name : run pytest
        run: |
           export DISPLAY=:99
           chromedriver --url-base=/wd/hub &
           sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
           pytest -p no:warnings 
    
